FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    libboost-all-dev \
    libusb-1.0-0-dev \
    python3 \
    python3-pip \
    python3-dev \
    software-properties-common && \
    \
    add-apt-repository -y ppa:ettusresearch/uhd && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    libuhd-dev \
    uhd-host && \
    \
    uhd_images_downloader && \
    \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Non Root user creation
RUN useradd -ms /bin/bash oaiuser
USER oaiuser

WORKDIR /app

# CMD ["bash"]
